# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaomesa',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='composicaomesa',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início'),
        ),
    ]
