# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0021_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoSessaoLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('sessao_legislativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.SessaoLegislativa')),
            ],
            options={
                'verbose_name_plural': 'Sessões Legislativas',
                'verbose_name': 'Sessão Legislativa',
            },
        ),
    ]
