# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0022_periodosessaolegislativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodosessaolegislativa',
            options={'verbose_name': 'Período Sessão Legislativa', 'verbose_name_plural': 'Períodos Sessões Legislativas'},
        ),
    ]
