# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0015_auto_20160929_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='assuntos',
            field=models.ManyToManyField(blank=True, through='norma.AssuntoNormaRelationship', to='norma.AssuntoNorma', verbose_name='Assuntos'),
        ),
    ]
